version: '3'
services:
  vtiger:
    build: .
    # image: php:7.0-fpm
    volumes:
     - ./htdocs:/srv/web
     - ./conf/php-fpm.conf.conf:/usr/local/etc/php-fpm.conf
    restart: always

  mysql:
    image: "mysql:5.5"
    volumes:
     - ./mysql_db:/var/lib/mysql
    environment:
      MYSQL_USER: vtiger
      MYSQL_PASSWORD: vtiger-db-password
      MYSQL_ROOT_PASSWORD: vtiger-root-db-password
      MYSQL_DATABASE: vtiger
    restart: always

  nginx:
    image: "nginx:latest"
    volumes:
     - ./htdocs:/srv/web
     - ./conf/snippets:/etc/nginx/snippets
     - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
    restart: always
    labels:
     - "traefik.enable=true"
     - "traefik.port=80"
     - "traefik.backend=vtiger-nginx"
     - "traefik.frontend.rule=Host:localhost"
